/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 25-ago.-2023 06:42:13 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS articulo_id_seq
;

DROP SEQUENCE IF EXISTS categoria_id_seq
;

DROP SEQUENCE IF EXISTS elemento_id_seq
;

DROP SEQUENCE IF EXISTS estado_elemento_id_seq
;

DROP SEQUENCE IF EXISTS evento_id_seq
;

DROP SEQUENCE IF EXISTS jerarquia_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Articulo" CASCADE
;

DROP TABLE IF EXISTS "Categoria" CASCADE
;

DROP TABLE IF EXISTS "Elemento" CASCADE
;

DROP TABLE IF EXISTS "Entrega" CASCADE
;

DROP TABLE IF EXISTS "Entrega_Personas" CASCADE
;

DROP TABLE IF EXISTS "Estado_Elemento" CASCADE
;

DROP TABLE IF EXISTS "Estado_persona" CASCADE
;

DROP TABLE IF EXISTS "Evento" CASCADE
;

DROP TABLE IF EXISTS "Hallazgo" CASCADE
;

DROP TABLE IF EXISTS "Hallazgo_Personas" CASCADE
;

DROP TABLE IF EXISTS "Instructor" CASCADE
;

DROP TABLE IF EXISTS "Jerarquia" CASCADE
;

DROP TABLE IF EXISTS "Permiso" CASCADE
;

DROP TABLE IF EXISTS "Permiso_Permiso" CASCADE
;

DROP TABLE IF EXISTS "Persona" CASCADE
;

DROP TABLE IF EXISTS "Rol" CASCADE
;

DROP TABLE IF EXISTS "Unidad" CASCADE
;

DROP TABLE IF EXISTS "Ursa" CASCADE
;

DROP TABLE IF EXISTS "Usuario" CASCADE
;

DROP TABLE IF EXISTS "Usuario_Permiso" CASCADE
;

/* Create Tables */

CREATE TABLE "Articulo"
(
	"Nombre" varchar(100) NULL,
	"Id" integer NOT NULL   DEFAULT NEXTVAL(('"articulo_id_seq"'::text)::regclass),
	"IdCategoria" integer NOT NULL
)
;

CREATE TABLE "Categoria"
(
	"Nombre" varchar NULL,
	"Id" integer NOT NULL   DEFAULT NEXTVAL(('"categoria_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Elemento"
(
	"Cantidad" varchar NULL,
	"Descripcion" varchar NULL,
	"Id" integer NOT NULL   DEFAULT NEXTVAL(('"elemento_id_seq"'::text)::regclass),
	"IdArticulo" integer NULL,
	"IdEstadoElemento" integer NULL,
	"IdHallazgo" integer NOT NULL,
	"IdEntrega" integer NULL
)
;

CREATE TABLE "Entrega"
(
	"FechaEntrega" timestamp without time zone NULL,
	"Id" integer NOT NULL,
	"Nroacta" varchar(200) NULL,
	"IdUnidad" integer NULL,
	"Observacion" varchar(200) NULL
)
;

CREATE TABLE "Entrega_Personas"
(
	"IdEstado" integer NULL,
	"IdEntrega" integer NOT NULL,
	"IdPersona" integer NOT NULL
)
;

CREATE TABLE "Estado_Elemento"
(
	"Nombre" varchar(200) NULL,
	"Id" integer NOT NULL   DEFAULT NEXTVAL(('"estado_elemento_id_seq"'::text)::regclass)
)
;

CREATE TABLE "Estado_persona"
(
	"Id" integer NOT NULL,
	"Nombre" varchar(50) NULL
)
;

CREATE TABLE "Evento"
(
	"Id" integer NOT NULL   DEFAULT NEXTVAL(('"evento_id_seq"'::text)::regclass),
	"Fecha" timestamp without time zone NULL,
	"Mensaje" varchar(200) NULL,
	"Usuario" varchar(50) NULL
)
;

CREATE TABLE "Hallazgo"
(
	"Id" integer NOT NULL,
	"IdUnidad" integer NULL,
	"Fechahallazgo" varchar NULL,
	"Lugarhallazgo" varchar NULL
)
;

CREATE TABLE "Hallazgo_Personas"
(
	"IdEstado" integer NULL,
	"IdHallazgo" integer NOT NULL,
	"IdPersona" integer NOT NULL
)
;

CREATE TABLE "Instructor"
(
	"Legajo" varchar NULL,
	"InstructorID" integer NOT NULL,
	"IdJerarquia" integer NULL
)
;

CREATE TABLE "Jerarquia"
(
	"Id" integer NOT NULL   DEFAULT NEXTVAL(('"jerarquia_id_seq"'::text)::regclass),
	"Abreviatura" varchar(100) NULL,
	"Jerarquia" varchar(100) NULL
)
;

CREATE TABLE "Permiso"
(
	"Id" integer NOT NULL,
	"Nombre" varchar(50) NULL,
	"EsPermiso" boolean NULL,
	"Descripcion" varchar(200) NULL,
	"IdPemisoPadre" integer NULL,
	"IdPermisoHijo" integer NULL
)
;

CREATE TABLE "Permiso_Permiso"
(
	"IdPemisoPadre" integer NOT NULL,
	"IdPermisoHijo" integer NOT NULL
)
;

CREATE TABLE "Persona"
(
	"Id" integer NOT NULL,
	"DNI" varchar(10) NULL,
	"Domicilio" varchar(200) NULL,
	"NombreCompleto" varchar(300) NULL,
	"Ocupacion" varchar(300) NULL,
	"Telefono" varchar(50) NULL,
	"Legajo" integer NULL,
	"IdJerarquia" integer NULL
)
;

CREATE TABLE "Rol"
(
	"Id" integer NOT NULL,
	"Nombre" varchar(200) NULL
)
;

CREATE TABLE "Unidad"
(
	"Id" integer NOT NULL,
	"IdUrsa" integer NOT NULL,
	"Nombre" varchar(50) NULL,
	"Cod" varchar(3) NULL
)
;

CREATE TABLE "Ursa"
(
	"Id" integer NOT NULL,
	"Nombre" varchar(50) NULL
)
;

CREATE TABLE "Usuario"
(
	"Id" integer NOT NULL,
	"NombreUsuario" varchar(200) NULL,
	"Password" varchar(50) NULL,
	"IdUrsa" integer NULL,
	"IdUnidad" integer NULL,
	"DNI" varchar(200) NULL
)
;

CREATE TABLE "Usuario_Permiso"
(
	"IdUsuario" integer NOT NULL,
	"IdPermiso" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Articulo" ADD CONSTRAINT "PK_Articulo"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Categoria" ADD CONSTRAINT "PK_Categoria"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Elemento" ADD CONSTRAINT "PK_Elemento"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Entrega" ADD CONSTRAINT "PK_Entrega"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Entrega_Personas" ADD CONSTRAINT "PK_Entrega_Personas"
	PRIMARY KEY ("IdEntrega","IdPersona")
;

ALTER TABLE "Estado_Elemento" ADD CONSTRAINT "PK_Estado_elemento"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Estado_persona" ADD CONSTRAINT "PK_Estado_persona"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Evento" ADD CONSTRAINT "PK_Evento"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Hallazgo" ADD CONSTRAINT "PK_Hallazgo"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Hallazgo_Personas" ADD CONSTRAINT "PK_Hallazgo_Personas"
	PRIMARY KEY ("IdHallazgo","IdPersona")
;

ALTER TABLE "Instructor" ADD CONSTRAINT "PK_Instructor"
	PRIMARY KEY ("InstructorID")
;

ALTER TABLE "Jerarquia" ADD CONSTRAINT "PK_Jerarquia"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Permiso" ADD CONSTRAINT "PK_Permiso"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Permiso_Permiso" ADD CONSTRAINT "PK_Permiso_Permiso"
	PRIMARY KEY ("IdPemisoPadre","IdPermisoHijo")
;

ALTER TABLE "Persona" ADD CONSTRAINT "PK_Persona"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Rol" ADD CONSTRAINT "PK_Rol"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Unidad" ADD CONSTRAINT "PK_Unidad"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Ursa" ADD CONSTRAINT "PK_Ursa"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Usuario" ADD CONSTRAINT "PK_Usuario"
	PRIMARY KEY ("Id")
;

ALTER TABLE "Usuario_Permiso" ADD CONSTRAINT "PK_Usuario_Permiso"
	PRIMARY KEY ("IdPermiso","IdUsuario")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Articulo" ADD CONSTRAINT "FK_Articulo_Categoria"
	FOREIGN KEY ("IdCategoria") REFERENCES "Categoria" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Elemento" ADD CONSTRAINT "FK_Elemento_Articulo"
	FOREIGN KEY ("IdArticulo") REFERENCES "Articulo" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Elemento" ADD CONSTRAINT "FK_Elemento_Estado_elemento"
	FOREIGN KEY ("IdEstadoElemento") REFERENCES "Estado_Elemento" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Elemento" ADD CONSTRAINT "FK_Elemento_Hallazgo"
	FOREIGN KEY ("IdHallazgo") REFERENCES "Hallazgo" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Elemento" ADD CONSTRAINT "FK_Elemento_Entrega"
	FOREIGN KEY ("IdEntrega") REFERENCES "Entrega" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Entrega" ADD CONSTRAINT "FK_Entrega_Unidad"
	FOREIGN KEY ("IdUnidad") REFERENCES "Unidad" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Entrega_Personas" ADD CONSTRAINT "FK_Entrega_Persona_Estado_persona"
	FOREIGN KEY ("IdEstado") REFERENCES "Estado_persona" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Entrega_Personas" ADD CONSTRAINT "FK_Entrega_Personas_Entrega"
	FOREIGN KEY ("IdEntrega") REFERENCES "Entrega" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Entrega_Personas" ADD CONSTRAINT "FK_Entrega_Personas_Persona"
	FOREIGN KEY ("IdPersona") REFERENCES "Persona" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hallazgo" ADD CONSTRAINT "FK_Hallazgo_Unidad"
	FOREIGN KEY ("IdUnidad") REFERENCES "Unidad" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hallazgo_Personas" ADD CONSTRAINT "FK_Hallazgo_Personas_Hallazgo"
	FOREIGN KEY ("IdHallazgo") REFERENCES "Hallazgo" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hallazgo_Personas" ADD CONSTRAINT "FK_PersonaEstado_Persona_Estado_Persona"
	FOREIGN KEY ("IdEstado") REFERENCES "Estado_persona" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hallazgo_Personas" ADD CONSTRAINT "FK_Person_Hallazgo"
	FOREIGN KEY ("IdPersona") REFERENCES "Persona" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Instructor" ADD CONSTRAINT "FK_Instructor_Persona"
	FOREIGN KEY ("InstructorID") REFERENCES "Persona" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Instructor" ADD CONSTRAINT "FK_Instructor_Jerarquia"
	FOREIGN KEY ("IdJerarquia") REFERENCES "Jerarquia" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Permiso_Permiso" ADD CONSTRAINT "FK_Permiso_Permiso_Permiso"
	FOREIGN KEY ("IdPemisoPadre") REFERENCES "Permiso" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Permiso_Permiso" ADD CONSTRAINT "FK_Permiso_Permiso_Permiso_02"
	FOREIGN KEY ("IdPermisoHijo") REFERENCES "Permiso" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Permiso_Permiso" ADD CONSTRAINT "FK_UsuarioComponente_Componente"
	FOREIGN KEY ("IdPemisoPadre") REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Permiso_Permiso" ADD CONSTRAINT "FK_UsuarioComponente_Usuario"
	FOREIGN KEY ("IdPermisoHijo") REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Persona" ADD CONSTRAINT "FK_Persona_Jerarquia"
	FOREIGN KEY ("IdJerarquia") REFERENCES "Jerarquia" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Unidad" ADD CONSTRAINT "FK_Unidad_Ursa"
	FOREIGN KEY ("IdUrsa") REFERENCES "Ursa" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Usuario" ADD CONSTRAINT "FK_Usuario_Unidad"
	FOREIGN KEY ("IdUnidad") REFERENCES "Unidad" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Usuario" ADD CONSTRAINT "FK_Usuario_Ursa"
	FOREIGN KEY ("IdUrsa") REFERENCES "Ursa" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Usuario_Permiso" ADD CONSTRAINT "FK_Usuario_Permiso_Permiso"
	FOREIGN KEY ("IdPermiso") REFERENCES "Permiso" ("Id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Usuario_Permiso" ADD CONSTRAINT "FK_Usuario_Permiso_Usuario"
	FOREIGN KEY ("IdUsuario") REFERENCES "Usuario" ("Id") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE articulo_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE categoria_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE elemento_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE estado_elemento_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE evento_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE jerarquia_id_seq INCREMENT 1 START 1
;
